// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `alpha_hint_from_header`, `has_png_transparency_blocking`, `read_prefix`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AlphaHint`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `eq`, `fmt`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<String?> deleteToTrash({required String filePath}) =>
    RustLib.instance.api.crateApiSimpleDeleteToTrash(filePath: filePath);

Future<String?> deleteAllToTrash({required List<String> filePaths}) =>
    RustLib.instance.api.crateApiSimpleDeleteAllToTrash(filePaths: filePaths);

Future<bool> hasPngTransparencyRust({required String filePath}) => RustLib
    .instance
    .api
    .crateApiSimpleHasPngTransparencyRust(filePath: filePath);

Future<List<String>> deleteTransparentPngsRust({
  required List<String> filePaths,
}) => RustLib.instance.api.crateApiSimpleDeleteTransparentPngsRust(
  filePaths: filePaths,
);
